spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource


    druid:
      # 默认数据源，oe本地数据库
      master:
        url: jdbc:mysql://localhost:3306/bcoc?useUnicode=true&characterEncoding=utf8
        username: root
        password: root123
      # esb日志库
      esbLogDb:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.18.231.40:8066/esb_jlyd?useUnicode=true&characterEncoding=utf8
        username: esb_jlyd
        password: esb_jlyd
      # esb配置库
      esbConfigDb:
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//172.18.238.234:1524/tthradb
        username: esbdb
        password: Paas#123


      #druid 数据源专有配置
      # 开启druid监控页面
      stat-view-servlet:
        enabled: true
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50

      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，比如不配置stat,我们在Druid的监控页面中就拿不到想要的信息。
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
